image: ubuntu:focal

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - export DUB=/usr/bin/dub
  - export TZ=Europe/London
  - apt-get -qq update
  - apt-get install -y dub ldc gdc libgtk-3-0 libfontconfig1 libpango1.0
  #  Need to add a couple of links manually.
  - ln -s /usr/bin/gcc-10 /usr/bin/gcc
  - ln -s /usr/bin/gcc /usr/bin/cc

run-test:
  script:
    - ldc2 --version
    - dub test --compiler=ldc2
