image: ubuntu:focal

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - export DUB=/usr/bin/dub
  - export TZ=Europe/London
  - apt-get -qq update
  - apt-get install -y dub ldc gdc libgtk-3-0 libfontconfig1 libpango1.0
  - ls -al /usr/bin/gcc*
  - update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 20

run-test:
  script:
    - dub test --compiler=ldc2
